### ISSUE TITLE
Brewing recipe mistakes

### ISSUE THREAD

**Issue by SylisMC** [Magick-Arcanist/Magick#3]
You have mistakes thought out the wiki brewing table. Glowstone is always stronger (Roman numerals), and Redstone is always longer (Plus symbol) but you've got them mixed up on the table really confused me for a hot min

![2022-09-24_19 34 29](https://user-images.githubusercontent.com/19602662/192122319-e5da09a9-d5b4-4438-9773-03a5d7c7e4b3.png)
![image](https://user-images.githubusercontent.com/19602662/192122305-735280c9-985b-4ac1-81f8-8e6438918e80.png)

Vanilla
![image](https://user-images.githubusercontent.com/19602662/192122359-d5a94420-6880-4495-8431-09bea31762a9.png)

**Comment by Magick-Arcanist** [comment]
Thank you, I've updated the image. Sorry for the confusion lol.

**Comment by SylisMC** [comment]
> Thank you, I've updated the image. Sorry for the confusion lol.

No no, its all good, thanks for all the hard work you put into MP&P for the community
